DNN.o: DNN.cpp
	g++ -c DNN.cpp
softmax.o: softmax.cpp 
	g++ -c softmax.cpp
relu.o: relu.cpp
	g++ -c relu.cpp
openblasmult.o: openblasmult.cpp helper.o
	g++ -c openblasmult.cpp
helper.o: helper.cpp
	g++ -c helper.cpp -o helper.o

